<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <PackageId>LGPD.Redact.Serialization</PackageId>
    <RootNamespace>LGPD.Redact.Serialization</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LGPD.Redact.Core" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>LGPD.Redact.Serialization.UnitTests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>